"""Initial schema from models

Revision ID: 8309e8168ff9
Revises: 
Create Date: 2025-06-11 11:02:13.540013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8309e8168ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_aid_MaterialCodeTagNo'), table_name='adjustind')
    op.alter_column('adjustinh', 'IsOutsource',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('adjustinh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_aih_AODocNo'), table_name='adjustinh')
    op.drop_index(op.f('IX_aih_DocDateStatusLocation'), table_name='adjustinh')
    op.alter_column('adjustouth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_aoh_DocDateStatusLocation'), table_name='adjustouth')
    op.drop_index(op.f('IX_APB_A'), table_name='apbook')
    op.drop_index(op.f('IX_apcgh_DocDateStatus'), table_name='apclearinggiroh')
    op.drop_index(op.f('IX_apcn_DocDateStatus'), table_name='apcreditnote')
    op.drop_index(op.f('IX_apdn_DocDateStatus'), table_name='apdebetnote')
    op.drop_index(op.f('IX_aprlh_DocDateStatus'), table_name='apreceiptlisth')
    op.drop_index(op.f('IX_aprg_DocDateStatus'), table_name='aprejectgiro')
    op.drop_index(op.f('IX_aps_APRecListNo'), table_name='apsettlement')
    op.drop_index(op.f('IX_aps_DocDateStatus'), table_name='apsettlement')
    op.drop_index(op.f('IX_ARB_A'), table_name='arbook')
    op.drop_index(op.f('IX_arcgh_DocDateStatus'), table_name='arclearinggiroh')
    op.drop_index(op.f('IX_arcn_DocDateStatus'), table_name='arcreditnote')
    op.drop_index(op.f('IX_ardn_DocDateStatus'), table_name='ardebetnote')
    op.alter_column('arperiode', 'IsClosed',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_arrg_DocDateStatus'), table_name='arrejectgiro')
    op.drop_index(op.f('IX_arrlh_DocDateStatus'), table_name='arrequestlisth')
    op.drop_index(op.f('IX_ars_ARReqListNo'), table_name='arsettlement')
    op.drop_index(op.f('IX_ars_DocDateStatus'), table_name='arsettlement')
    op.alter_column('asset', 'DepreciationRun',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('aucsettlement', 'DepreciationRun',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_aucs_DocDateStatus'), table_name='aucsettlement')
    op.drop_index(op.f('IX_bsh_DocDateStatusLocation'), table_name='bookstockh')
    op.drop_index(op.f('IX_bsh_SODocNo'), table_name='bookstockh')
    op.drop_index(op.f('IX_CashierPayment_A'), table_name='cashierpaymentd')
    op.drop_index(op.f('IX_cashph_APRecListNo'), table_name='cashierpaymenth')
    op.drop_index(op.f('IX_cashph_DocDateStatus'), table_name='cashierpaymenth')
    op.drop_index(op.f('IX_crh_ARReqListNo'), table_name='cashierreceipth')
    op.drop_index(op.f('IX_crh_DocDateStatus'), table_name='cashierreceipth')
    op.alter_column('changepriceh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_cpd_ARDocNo'), table_name='customerpaymentd')
    op.drop_index(op.f('IX_cph_ARReqListNo'), table_name='customerpaymenth')
    op.drop_index(op.f('IX_cph_DocDateStatus'), table_name='customerpaymenth')
    op.alter_column('customervisitd', 'IsScheduled',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('customervisitd', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('customervisitd', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('customervisith', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('customervisith', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('IX_cvh_DocDateStatusLocation'), table_name='customervisith')
    op.alter_column('cyclecounth', 'UseTagNo',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('cyclecounth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_cch_DocDateStatusLocation'), table_name='cyclecounth')
    op.alter_column('datalog', 'LogTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('IX_DataLog_A'), table_name='datalog')
    op.alter_column('datatransferlog', 'AllowChange',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('datatransferlogsummary', 'Error',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('IX_dpd_APDocNo'), table_name='debtpaymentd')
    op.drop_index(op.f('IX_DPH_APRecListNo'), table_name='debtpaymenth')
    op.drop_index(op.f('IX_dph_DocDateStatus'), table_name='debtpaymenth')
    op.drop_index(op.f('IX_drh_DocDateStatusLocation'), table_name='deliveryreturnh')
    op.drop_index(op.f('IX_drh_GIDocNo'), table_name='deliveryreturnh')
    op.alter_column('dialogcustomization', 'SimpleMode',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('employeegps', 'GPSTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsFilter',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsSelect',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsLookup',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsRequired',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsEditable',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansionhook', 'Enabled',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('expansionhook', 'References',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('expansionhook', 'SourceCode',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('expansionui', 'IsDetail',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_gih_CustomerCodeStatus'), table_name='goodsissueh')
    op.drop_index(op.f('IX_gih_DocDateStatusLocation'), table_name='goodsissueh')
    op.drop_index(op.f('IX_gih_SODocNo'), table_name='goodsissueh')
    op.drop_index(op.f('IX_GRD_TagNo'), table_name='goodsreceiptd')
    op.drop_index(op.f('IX_grh_DocDateStatusLocation'), table_name='goodsreceipth')
    op.drop_index(op.f('IX_grh_PODocNo'), table_name='goodsreceipth')
    op.alter_column('hrattendance', 'IsValid',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrattendanceoriginal', 'IsValid',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrchangeshifth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrgeneratequotah', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrirregularpaymenth', 'IsDeduction',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrirregularpaymenth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrloand', 'IsPaidAutomatic',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrloand', 'IsPaidManual',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrloanh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrovertimed', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('hrovertimed', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('hrovertimeh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrpayroll', 'IsFinal',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('hrpermissiond', 'WorkingStartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'WorkingEndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break1StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break1EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break2StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break2EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('hrpermissionh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('joborder', 'ActualStartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('joborder', 'ActualFinishTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('joborder', 'ExcludeCostDistribution',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('joborder', 'CheckQtyOutput',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_JobOrder_A'), table_name='joborder')
    op.drop_index(op.f('IX_jo_IODocNo'), table_name='joborder')
    op.drop_index(op.f('IX_jo_PlannedStartDateStatusLocation'), table_name='joborder')
    op.drop_index(op.f('IX_jo_SODocNo'), table_name='joborder')
    op.drop_index(op.f('IX_jo_WODocNo'), table_name='joborder')
    op.drop_index(op.f('IX_JRD_TagNo'), table_name='jobresultd')
    op.alter_column('jobresultdt', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('jobresultdt', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('jobresulth', 'DocTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('IX_JRH_DocDate'), table_name='jobresulth')
    op.drop_index(op.f('IX_JRH_JODocNo'), table_name='jobresulth')
    op.drop_index(op.f('IX_jrh_DocDateStatusLocation'), table_name='jobresulth')
    op.alter_column('masteraccount', 'Level',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('masteraccount', 'IsJournal',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masteraccount', 'IsCashier',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterbomh', 'IsAverageCOGM',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterchatbotschedule', 'Enabled',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterchatbotschedule', 'Multicast',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomer', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomer', 'IsBlacklisted',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomer', 'IsDeleted',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('FK_mastercustomer_msa1'), table_name='mastercustomer')
    op.alter_column('mastercustomervisitscheduled', 'Sunday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Monday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Tuesday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Wednesday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Thursday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Friday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Saturday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterdashboardh', 'Layout',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('masterdashboardh', 'InitializationCode',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('masterdashboarditem', 'Query',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('masterdashboarditem', 'LayoutCode',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('masterdatatransfer', 'WithDetail',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterdocumentseries', 'NeedQC',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterdocumentseries', 'NoTaxNo',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterdocumentseries', 'AutoTaxNo',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_Series'), table_name='masterdocumentseries')
    op.alter_column('masteremployeee', 'IsCompleted',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masteremployeeh', 'IsActive',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masteremployeev', 'BoolValue',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('masterformshortcut', 'Ctrl',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterformshortcut', 'Alt',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrcomponent', 'IsSaveToDatabase',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrorganizationalunit', 'IsLeaf',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsQuotaValueEditable',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsMultiDays',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsSkipHoliday',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsNoAttendance',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsPaid',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsLossTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixShift',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixWorkingStartTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixWorkingEndTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak1StartTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak1EndTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak2StartTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak2EndTime',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixValid',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsAllowNegative',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsAutomaticRollOver',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsProportional',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'WorkingStartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'WorkingEndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break1StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break1EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break2StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break2EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterhrvariable', 'IsRequired',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterhrvariable', 'IsSystem',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterlocation', 'IsWarehouseManagement',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterlocation', 'IsQualityControl',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsBatch',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsService',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsAsset',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_MasterMaterial_A'), table_name='mastermaterial')
    op.alter_column('mastermaterialtype', 'IsWaste',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermobilereporth', 'Query',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('mastermobilereporth', 'Javascript',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('mastermpshop', 'IsDownload',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastermpstatus', 'CanCreateSO',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterperiode', 'IsClosed',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'IsSuggested',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'ExcludeRequirement',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'MustMultiple',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterrangeselector', 'SimpleMode',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterreminder', 'Query',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('masterreporth', 'Enabled',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterreportscheduleh', 'IsEnabled',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterreportschedulet', 'Time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('mastersupplier', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastersurveya', 'IsAllowFreeText',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastertransactionh', 'IsApprovable',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('mastertransactionh', 'IsPrintable',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterunitconversion', 'IsInactive',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('masterworkordertemplateh', 'CheckQtyOutput',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_MUD_TagNo'), table_name='materialusaged')
    op.alter_column('materialusagegeneratord', 'DocTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('materialusagegeneratordt', 'StartTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('materialusagegeneratordt', 'EndTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('materialusagegeneratorh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_mugh_DocDateStatusLocation'), table_name='materialusagegeneratorh')
    op.alter_column('materialusageh', 'DocTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('IX_MUH_JODocNo'), table_name='materialusageh')
    op.drop_index(op.f('IX_muh_DocDateStatusLocation'), table_name='materialusageh')
    op.drop_index(op.f('IX_murh_DocDateStatusLocation'), table_name='materialusagereturnh')
    op.drop_index(op.f('IX_murh_JODocNo'), table_name='materialusagereturnh')
    op.drop_index(op.f('IX_murh_MUDocNo'), table_name='materialusagereturnh')
    op.drop_index(op.f('IX_MPOrderH_A'), table_name='mporderh')
    op.drop_index(op.f('IX_MPOrderH_B'), table_name='mporderh')
    op.drop_index(op.f('IX_plh_DocDateStatus'), table_name='packinglisth')
    op.drop_index(op.f('IX_posh_DocDateStatus'), table_name='pointofsaleh')
    op.alter_column('posstartbalanceh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_possbh_DocDateStatus'), table_name='posstartbalanceh')
    op.drop_index(op.f('IX_profinvh_DocDateStatus'), table_name='proformainvoiceh')
    op.drop_index(op.f('IX_profinvh_SODocNo'), table_name='proformainvoiceh')
    op.alter_column('purchasecosth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_pch_DocDateStatus'), table_name='purchasecosth')
    op.alter_column('purchaseinvoiceh', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_PurchaseInvoice_A'), table_name='purchaseinvoiceh')
    op.drop_index(op.f('IX_pih_DocDateStatus'), table_name='purchaseinvoiceh')
    op.drop_index(op.f('IX_pih_GRDocNo'), table_name='purchaseinvoiceh')
    op.alter_column('purchaseorderh', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('purchaseorderh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('purchaseorderh', 'IsSalesReturn',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_poh_DocDateStatus'), table_name='purchaseorderh')
    op.drop_index(op.f('IX_poh_JODocNo'), table_name='purchaseorderh')
    op.alter_column('purchaserequesth', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_prh_DocDateStatus'), table_name='purchaserequesth')
    op.drop_index(op.f('IX_prh_JODocNo'), table_name='purchaserequesth')
    op.drop_index(op.f('IX_prtnh_DocDateStatus'), table_name='purchasereturnh')
    op.drop_index(op.f('IX_prtnh_GIDocNo'), table_name='purchasereturnh')
    op.alter_column('reportmanagement', 'IsNoShowGrid',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('reportmanagement', 'IsNoPrint',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('reportmanagement', 'IsNoExport',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_ReportRequest_A'), table_name='reportrequest')
    op.alter_column('salesinvoiceh', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_sih_DocDateStatus'), table_name='salesinvoiceh')
    op.drop_index(op.f('IX_sih_GIDocNo'), table_name='salesinvoiceh')
    op.alter_column('salesorderh', 'CutPPh',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('salesorderh', 'IsPurchaseReturn',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('salesorderh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('FK_salesorderh_ms'), table_name='salesorderh')
    op.drop_index(op.f('IX_soh_CustomerCodeStatus'), table_name='salesorderh')
    op.drop_index(op.f('IX_soh_DocDateStatus'), table_name='salesorderh')
    op.drop_index(op.f('IX_srh_DocDateStatus'), table_name='salesreturnh')
    op.drop_index(op.f('IX_srh_GRDocNo'), table_name='salesreturnh')
    op.alter_column('scheduledjournalh', 'IsEndOfMonth',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_sh_DocDateStatus'), table_name='shipmenth')
    op.alter_column('shortcut', 'Ctrl',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('shortcut', 'Alt',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_smla_GRDocNo'), table_name='smladjustment')
    op.drop_index(op.f('IX_smla_PIDocNo'), table_name='smladjustment')
    op.drop_index(op.f('IX_smla_PODocNo'), table_name='smladjustment')
    op.drop_index(op.f('IX_smled_DocNo'), table_name='smlexcludeddocument')
    op.drop_index(op.f('IX_smled_GIDocNo'), table_name='smlexcludeddocument')
    op.drop_index(op.f('IX_smled_SODocNo'), table_name='smlexcludeddocument')
    op.drop_index(op.f('IX_Stock_DocDate'), table_name='stock')
    op.drop_index(op.f('IX_stock_DocNo'), table_name='stock')
    op.drop_index(op.f('IX_SB_MaterialCode_TagNo'), table_name='stockbalance')
    op.drop_index(op.f('IX_sth_DocDateStatusFromLocation'), table_name='stocktransferh')
    op.drop_index(op.f('IX_sth_RequestDocNo'), table_name='stocktransferh')
    op.drop_index(op.f('IX_strh_DocDateStatusToLocation'), table_name='stocktransferrequesth')
    op.drop_index(op.f('IX_toh_DocDateStatusLocation'), table_name='transferorderh')
    op.drop_index(op.f('IX_toh_RefDocNo'), table_name='transferorderh')
    op.alter_column('transportdeliveryorderd', 'Returned',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('transportsalesorderh', 'IsRent',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_TSOH_A'), table_name='transportsalesorderh')
    op.alter_column('transportsalesrequesth', 'Pickup',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('userlog', 'LogTime',
               existing_type=mysql.TIME(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('IX_wmtih_DocDateStatusLocation'), table_name='wmtransferinh')
    op.drop_index(op.f('IX_wmtih_WMTODocNo'), table_name='wmtransferinh')
    op.drop_index(op.f('IX_wmtoh_DocDateStatusFromLocation'), table_name='wmtransferouth')
    op.drop_index(op.f('IX_wmtoh_RequestDocNo'), table_name='wmtransferouth')
    op.alter_column('workorderh', 'CheckQtyOutput',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('workorderh', 'IsApproved',
               existing_type=mysql.BIT(length=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.drop_index(op.f('IX_woh_DocDateStatusMaterialCode'), table_name='workorderh')
    op.drop_index(op.f('IX_woh_SODocNo'), table_name='workorderh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('IX_woh_SODocNo'), 'workorderh', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_woh_DocDateStatusMaterialCode'), 'workorderh', ['DocDate', 'Status', 'MaterialCode'], unique=False)
    op.alter_column('workorderh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('workorderh', 'CheckQtyOutput',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_wmtoh_RequestDocNo'), 'wmtransferouth', ['RequestDocNo'], unique=False)
    op.create_index(op.f('IX_wmtoh_DocDateStatusFromLocation'), 'wmtransferouth', ['DocDate', 'Status', 'FromLocation'], unique=False)
    op.create_index(op.f('IX_wmtih_WMTODocNo'), 'wmtransferinh', ['WMTODocNo'], unique=False)
    op.create_index(op.f('IX_wmtih_DocDateStatusLocation'), 'wmtransferinh', ['DocDate', 'Status', 'Location'], unique=False)
    op.alter_column('userlog', 'LogTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('transportsalesrequesth', 'Pickup',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_TSOH_A'), 'transportsalesorderh', ['TSIDocNo'], unique=False)
    op.alter_column('transportsalesorderh', 'IsRent',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('transportdeliveryorderd', 'Returned',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_toh_RefDocNo'), 'transferorderh', ['RefDocNo'], unique=False)
    op.create_index(op.f('IX_toh_DocDateStatusLocation'), 'transferorderh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_strh_DocDateStatusToLocation'), 'stocktransferrequesth', ['DocDate', 'Status', 'ToLocation'], unique=False)
    op.create_index(op.f('IX_sth_RequestDocNo'), 'stocktransferh', ['RequestDocNo'], unique=False)
    op.create_index(op.f('IX_sth_DocDateStatusFromLocation'), 'stocktransferh', ['DocDate', 'Status', 'FromLocation'], unique=False)
    op.create_index(op.f('IX_SB_MaterialCode_TagNo'), 'stockbalance', ['MaterialCode', 'TagNo'], unique=False)
    op.create_index(op.f('IX_stock_DocNo'), 'stock', ['DocNo'], unique=False)
    op.create_index(op.f('IX_Stock_DocDate'), 'stock', ['MaterialCode', 'DocDate', 'Location'], unique=False)
    op.create_index(op.f('IX_smled_SODocNo'), 'smlexcludeddocument', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_smled_GIDocNo'), 'smlexcludeddocument', ['GIDocNo'], unique=False)
    op.create_index(op.f('IX_smled_DocNo'), 'smlexcludeddocument', ['DocNo'], unique=False)
    op.create_index(op.f('IX_smla_PODocNo'), 'smladjustment', ['PODocNo'], unique=False)
    op.create_index(op.f('IX_smla_PIDocNo'), 'smladjustment', ['PIDocNo'], unique=False)
    op.create_index(op.f('IX_smla_GRDocNo'), 'smladjustment', ['GRDocNo'], unique=False)
    op.alter_column('shortcut', 'Alt',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('shortcut', 'Ctrl',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_sh_DocDateStatus'), 'shipmenth', ['DocDate', 'Status'], unique=False)
    op.alter_column('scheduledjournalh', 'IsEndOfMonth',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_srh_GRDocNo'), 'salesreturnh', ['GRDocNo'], unique=False)
    op.create_index(op.f('IX_srh_DocDateStatus'), 'salesreturnh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_soh_DocDateStatus'), 'salesorderh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_soh_CustomerCodeStatus'), 'salesorderh', ['CustomerCode', 'Status'], unique=False)
    op.create_index(op.f('FK_salesorderh_ms'), 'salesorderh', ['SalesCode'], unique=False)
    op.alter_column('salesorderh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('salesorderh', 'IsPurchaseReturn',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('salesorderh', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_sih_GIDocNo'), 'salesinvoiceh', ['GIDocNo'], unique=False)
    op.create_index(op.f('IX_sih_DocDateStatus'), 'salesinvoiceh', ['DocDate', 'Status'], unique=False)
    op.alter_column('salesinvoiceh', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_ReportRequest_A'), 'reportrequest', ['Status'], unique=False)
    op.alter_column('reportmanagement', 'IsNoExport',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('reportmanagement', 'IsNoPrint',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('reportmanagement', 'IsNoShowGrid',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_prtnh_GIDocNo'), 'purchasereturnh', ['GIDocNo'], unique=False)
    op.create_index(op.f('IX_prtnh_DocDateStatus'), 'purchasereturnh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_prh_JODocNo'), 'purchaserequesth', ['JODocNo'], unique=False)
    op.create_index(op.f('IX_prh_DocDateStatus'), 'purchaserequesth', ['DocDate', 'Status'], unique=False)
    op.alter_column('purchaserequesth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_poh_JODocNo'), 'purchaseorderh', ['JODocNo'], unique=False)
    op.create_index(op.f('IX_poh_DocDateStatus'), 'purchaseorderh', ['DocDate', 'Status'], unique=False)
    op.alter_column('purchaseorderh', 'IsSalesReturn',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('purchaseorderh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('purchaseorderh', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_pih_GRDocNo'), 'purchaseinvoiceh', ['GRDocNo'], unique=False)
    op.create_index(op.f('IX_pih_DocDateStatus'), 'purchaseinvoiceh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_PurchaseInvoice_A'), 'purchaseinvoiceh', ['JODocNo'], unique=False)
    op.alter_column('purchaseinvoiceh', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_pch_DocDateStatus'), 'purchasecosth', ['DocDate', 'Status'], unique=False)
    op.alter_column('purchasecosth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_profinvh_SODocNo'), 'proformainvoiceh', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_profinvh_DocDateStatus'), 'proformainvoiceh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_possbh_DocDateStatus'), 'posstartbalanceh', ['DocDate', 'Status'], unique=False)
    op.alter_column('posstartbalanceh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_posh_DocDateStatus'), 'pointofsaleh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_plh_DocDateStatus'), 'packinglisth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_MPOrderH_B'), 'mporderh', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_MPOrderH_A'), 'mporderh', ['DocDate'], unique=False)
    op.create_index(op.f('IX_murh_MUDocNo'), 'materialusagereturnh', ['MUDocNo'], unique=False)
    op.create_index(op.f('IX_murh_JODocNo'), 'materialusagereturnh', ['JODocNo'], unique=False)
    op.create_index(op.f('IX_murh_DocDateStatusLocation'), 'materialusagereturnh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_muh_DocDateStatusLocation'), 'materialusageh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_MUH_JODocNo'), 'materialusageh', ['JODocNo'], unique=False)
    op.alter_column('materialusageh', 'DocTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.create_index(op.f('IX_mugh_DocDateStatusLocation'), 'materialusagegeneratorh', ['DocDate', 'Status', 'Location'], unique=False)
    op.alter_column('materialusagegeneratorh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('materialusagegeneratordt', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('materialusagegeneratordt', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('materialusagegeneratord', 'DocTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.create_index(op.f('IX_MUD_TagNo'), 'materialusaged', ['TagNo'], unique=False)
    op.alter_column('masterworkordertemplateh', 'CheckQtyOutput',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterunitconversion', 'IsInactive',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastertransactionh', 'IsPrintable',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastertransactionh', 'IsApprovable',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastersurveya', 'IsAllowFreeText',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastersupplier', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterreportschedulet', 'Time',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterreportscheduleh', 'IsEnabled',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterreporth', 'Enabled',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterreminder', 'Query',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('masterrangeselector', 'SimpleMode',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'MustMultiple',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'ExcludeRequirement',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'IsSuggested',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterpromoh', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterperiode', 'IsClosed',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermpstatus', 'CanCreateSO',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermpshop', 'IsDownload',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermobilereporth', 'Javascript',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('mastermobilereporth', 'Query',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('mastermaterialtype', 'IsWaste',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_MasterMaterial_A'), 'mastermaterial', ['Type'], unique=False)
    op.alter_column('mastermaterial', 'IsPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsAsset',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsService',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastermaterial', 'IsBatch',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterlocation', 'IsQualityControl',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterlocation', 'IsWarehouseManagement',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrvariable', 'IsSystem',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrvariable', 'IsRequired',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break2EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break2StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break1EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'Break1StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'WorkingEndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrshift', 'WorkingStartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsProportional',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsAutomaticRollOver',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrquota', 'IsAllowNegative',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixValid',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak2EndTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak2StartTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak1EndTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixBreak1StartTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixWorkingEndTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixWorkingStartTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsFixShift',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsLossTime',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsPaid',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsNoAttendance',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsSkipHoliday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsMultiDays',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrpermissiontype', 'IsQuotaValueEditable',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrorganizationalunit', 'IsLeaf',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterhrcomponent', 'IsSaveToDatabase',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterformshortcut', 'Alt',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterformshortcut', 'Ctrl',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masteremployeev', 'BoolValue',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=True)
    op.alter_column('masteremployeeh', 'IsActive',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masteremployeee', 'IsCompleted',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_Series'), 'masterdocumentseries', ['Series'], unique=True)
    op.alter_column('masterdocumentseries', 'AutoTaxNo',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterdocumentseries', 'NoTaxNo',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterdocumentseries', 'NeedQC',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterdatatransfer', 'WithDetail',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterdashboarditem', 'LayoutCode',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('masterdashboarditem', 'Query',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('masterdashboardh', 'InitializationCode',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('masterdashboardh', 'Layout',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Saturday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Friday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Thursday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Wednesday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Tuesday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Monday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomervisitscheduled', 'Sunday',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('FK_mastercustomer_msa1'), 'mastercustomer', ['SalesArea1'], unique=False)
    op.alter_column('mastercustomer', 'IsDeleted',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomer', 'IsBlacklisted',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('mastercustomer', 'CutPPh',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterchatbotschedule', 'Multicast',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterchatbotschedule', 'Enabled',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masterbomh', 'IsAverageCOGM',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masteraccount', 'IsCashier',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masteraccount', 'IsJournal',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('masteraccount', 'Level',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)
    op.create_index(op.f('IX_jrh_DocDateStatusLocation'), 'jobresulth', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_JRH_JODocNo'), 'jobresulth', ['JODocNo'], unique=False)
    op.create_index(op.f('IX_JRH_DocDate'), 'jobresulth', ['DocDate'], unique=False)
    op.alter_column('jobresulth', 'DocTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('jobresultdt', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('jobresultdt', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.create_index(op.f('IX_JRD_TagNo'), 'jobresultd', ['TagNo'], unique=False)
    op.create_index(op.f('IX_jo_WODocNo'), 'joborder', ['WODocNo'], unique=False)
    op.create_index(op.f('IX_jo_SODocNo'), 'joborder', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_jo_PlannedStartDateStatusLocation'), 'joborder', ['PlannedStartDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_jo_IODocNo'), 'joborder', ['IODocNo'], unique=False)
    op.create_index(op.f('IX_JobOrder_A'), 'joborder', ['ActualFinishDate', 'Status'], unique=False)
    op.alter_column('joborder', 'CheckQtyOutput',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('joborder', 'ExcludeCostDistribution',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('joborder', 'ActualFinishTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('joborder', 'ActualStartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('hrpermissionh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrpermissiond', 'Break2EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break2StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break1EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'Break1StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'WorkingEndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpermissiond', 'WorkingStartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('hrpayroll', 'IsFinal',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrovertimeh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrovertimed', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('hrovertimed', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('hrloanh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrloand', 'IsPaidManual',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrloand', 'IsPaidAutomatic',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrirregularpaymenth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrirregularpaymenth', 'IsDeduction',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrgeneratequotah', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrchangeshifth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrattendanceoriginal', 'IsValid',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('hrattendance', 'IsValid',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_grh_PODocNo'), 'goodsreceipth', ['PODocNo'], unique=False)
    op.create_index(op.f('IX_grh_DocDateStatusLocation'), 'goodsreceipth', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_GRD_TagNo'), 'goodsreceiptd', ['TagNo'], unique=False)
    op.create_index(op.f('IX_gih_SODocNo'), 'goodsissueh', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_gih_DocDateStatusLocation'), 'goodsissueh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_gih_CustomerCodeStatus'), 'goodsissueh', ['CustomerCode', 'Status'], unique=False)
    op.alter_column('expansionui', 'IsDetail',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansionhook', 'SourceCode',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('expansionhook', 'References',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('expansionhook', 'Enabled',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsEditable',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsRequired',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsLookup',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsSelect',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('expansiondefinition', 'IsFilter',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('employeegps', 'GPSTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('dialogcustomization', 'SimpleMode',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_drh_GIDocNo'), 'deliveryreturnh', ['GIDocNo'], unique=False)
    op.create_index(op.f('IX_drh_DocDateStatusLocation'), 'deliveryreturnh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_dph_DocDateStatus'), 'debtpaymenth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_DPH_APRecListNo'), 'debtpaymenth', ['APRecListNo'], unique=False)
    op.create_index(op.f('IX_dpd_APDocNo'), 'debtpaymentd', ['APDocNo'], unique=False)
    op.alter_column('datatransferlogsummary', 'Error',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('datatransferlog', 'AllowChange',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_DataLog_A'), 'datalog', ['LogDate'], unique=False)
    op.alter_column('datalog', 'LogTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.create_index(op.f('IX_cch_DocDateStatusLocation'), 'cyclecounth', ['DocDate', 'Status', 'Location'], unique=False)
    op.alter_column('cyclecounth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('cyclecounth', 'UseTagNo',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_cvh_DocDateStatusLocation'), 'customervisith', ['DocDate', 'Status', 'Location'], unique=False)
    op.alter_column('customervisith', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('customervisith', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('customervisitd', 'EndTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('customervisitd', 'StartTime',
               existing_type=sa.String(length=255),
               type_=mysql.TIME(),
               existing_nullable=True)
    op.alter_column('customervisitd', 'IsScheduled',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_cph_DocDateStatus'), 'customerpaymenth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_cph_ARReqListNo'), 'customerpaymenth', ['ARReqListNo'], unique=False)
    op.create_index(op.f('IX_cpd_ARDocNo'), 'customerpaymentd', ['ARDocNo'], unique=False)
    op.alter_column('changepriceh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_crh_DocDateStatus'), 'cashierreceipth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_crh_ARReqListNo'), 'cashierreceipth', ['ARReqListNo'], unique=False)
    op.create_index(op.f('IX_cashph_DocDateStatus'), 'cashierpaymenth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_cashph_APRecListNo'), 'cashierpaymenth', ['APRecListNo'], unique=False)
    op.create_index(op.f('IX_CashierPayment_A'), 'cashierpaymentd', ['JODocNo'], unique=False)
    op.create_index(op.f('IX_bsh_SODocNo'), 'bookstockh', ['SODocNo'], unique=False)
    op.create_index(op.f('IX_bsh_DocDateStatusLocation'), 'bookstockh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_aucs_DocDateStatus'), 'aucsettlement', ['DocDate', 'Status'], unique=False)
    op.alter_column('aucsettlement', 'DepreciationRun',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('asset', 'DepreciationRun',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_ars_DocDateStatus'), 'arsettlement', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_ars_ARReqListNo'), 'arsettlement', ['ARReqListNo'], unique=False)
    op.create_index(op.f('IX_arrlh_DocDateStatus'), 'arrequestlisth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_arrg_DocDateStatus'), 'arrejectgiro', ['DocDate', 'Status'], unique=False)
    op.alter_column('arperiode', 'IsClosed',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_ardn_DocDateStatus'), 'ardebetnote', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_arcn_DocDateStatus'), 'arcreditnote', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_arcgh_DocDateStatus'), 'arclearinggiroh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_ARB_A'), 'arbook', ['DocNo'], unique=False)
    op.create_index(op.f('IX_aps_DocDateStatus'), 'apsettlement', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_aps_APRecListNo'), 'apsettlement', ['APRecListNo'], unique=False)
    op.create_index(op.f('IX_aprg_DocDateStatus'), 'aprejectgiro', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_aprlh_DocDateStatus'), 'apreceiptlisth', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_apdn_DocDateStatus'), 'apdebetnote', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_apcn_DocDateStatus'), 'apcreditnote', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_apcgh_DocDateStatus'), 'apclearinggiroh', ['DocDate', 'Status'], unique=False)
    op.create_index(op.f('IX_APB_A'), 'apbook', ['DocNo'], unique=False)
    op.create_index(op.f('IX_aoh_DocDateStatusLocation'), 'adjustouth', ['DocDate', 'Status', 'Location'], unique=False)
    op.alter_column('adjustouth', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_aih_DocDateStatusLocation'), 'adjustinh', ['DocDate', 'Status', 'Location'], unique=False)
    op.create_index(op.f('IX_aih_AODocNo'), 'adjustinh', ['AODocNo'], unique=False)
    op.alter_column('adjustinh', 'IsApproved',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.alter_column('adjustinh', 'IsOutsource',
               existing_type=sa.Boolean(),
               type_=mysql.BIT(length=1),
               existing_nullable=False)
    op.create_index(op.f('IX_aid_MaterialCodeTagNo'), 'adjustind', ['MaterialCode', 'TagNo'], unique=False)
    # ### end Alembic commands ###
