# backend/app/db_models/purchase_models.py
from sqlalchemy import Column, String, Date, Integer, Numeric, ForeignKey, DateTime
from sqlalchemy.dialects.mysql import BIT
from sqlalchemy.orm import relationship
from .base import Base

class PurchaseOrderH(Base):
    __tablename__ = 'purchaseorderh'
    DocNo = Column(String(15), primary_key=True)
    Series = Column(String(3), nullable=False)
    TransactionType = Column(String(20), nullable=False)
    DocDate = Column(Date, nullable=False)
    SupplierCode = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierTaxTo = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    DeliveryDate = Column(Date, nullable=False)
    TOP = Column(Integer, nullable=False)
    DiscPercent = Column(Numeric(18, 4), nullable=False)
    TaxStatus = Column(String(10), nullable=False)
    TaxPercent = Column(Numeric(18, 4), nullable=False)
    Currency = Column(String(3), ForeignKey('mastercurrency.Code'), nullable=False)
    ExchangeRate = Column(Numeric(18, 4), nullable=False)
    JODocNo = Column(String(15), nullable=False)
    Trip = Column(String(20), nullable=False)
    SIDocNo = Column(String(15), nullable=False)
    TotalGross = Column(Numeric(18, 4), nullable=False)
    TotalDisc = Column(Numeric(18, 4), nullable=False)
    TaxValue = Column(Numeric(18, 4), nullable=False)
    TotalNetto = Column(Numeric(18, 4), nullable=False)
    CutPPh = Column(BIT, nullable=False)
    PPhPercent = Column(Numeric(18, 4), nullable=False)
    PPhValue = Column(Numeric(18, 4), nullable=False)
    SendTo = Column(String(50), nullable=False)
    Information = Column(String(255), nullable=False)
    Status = Column(String(20), nullable=False)
    IsApproved = Column(BIT, nullable=False)
    ApprovedBy = Column(String(16), nullable=True)
    ApprovedDate = Column(DateTime, nullable=True)
    PrintCounter = Column(Integer, nullable=False)
    PrintedBy = Column(String(16), nullable=True)
    PrintedDate = Column(DateTime, nullable=True)
    IsSalesReturn = Column(BIT, nullable=False)
    CreatedBy = Column(String(16), nullable=False)
    CreatedDate = Column(DateTime, nullable=False)
    ChangedBy = Column(String(16), nullable=False)
    ChangedDate = Column(DateTime, nullable=False)

    supplier_ref = relationship("MasterSupplier", foreign_keys=[SupplierCode], back_populates="purchase_orders")
    supplier_tax_to_ref = relationship("MasterSupplier", foreign_keys=[SupplierTaxTo], back_populates="tax_to_purchase_orders")
    currency_ref = relationship("MasterCurrency")
    details = relationship("PurchaseOrderD", back_populates="header", cascade="all, delete-orphan")
    goods_receipts = relationship("GoodsReceiptH", back_populates="purchase_order")

class PurchaseOrderD(Base):
    __tablename__ = 'purchaseorderd'
    DocNo = Column(String(15), ForeignKey('purchaseorderh.DocNo'), primary_key=True)
    Number = Column(Integer, primary_key=True)
    MaterialCode = Column(String(20), ForeignKey('mastermaterial.Code'), nullable=False)
    Info = Column(String(1024), nullable=False)
    Unit = Column(String(5), ForeignKey('masterunit.Code'), nullable=False)
    Qty = Column(Numeric(18, 4), nullable=False)
    Price = Column(Numeric(18, 4), nullable=False)
    Gross = Column(Numeric(18, 4), nullable=False)
    DiscPercent = Column(Numeric(18, 4), nullable=False)
    DiscPercent2 = Column(Numeric(18, 4), nullable=False)
    DiscPercent3 = Column(Numeric(18, 4), nullable=False)
    DiscValue = Column(Numeric(18, 4), nullable=False)
    DiscNominal = Column(Numeric(18, 4), nullable=False)
    Netto = Column(Numeric(18, 4), nullable=False)
    QtyReceived = Column(Numeric(18, 4), nullable=False)

    header = relationship("PurchaseOrderH", back_populates="details")
    material_ref = relationship("MasterMaterial")
    unit_ref = relationship("MasterUnit")

class PurchaseReturnH(Base):
    __tablename__ = 'purchasereturnh'

    DocNo = Column(String(15), primary_key=True)
    Series = Column(String(3), nullable=False)
    DocDate = Column(Date, nullable=False)
    SODocNo = Column(String(15), nullable=False)
    GIDocNo = Column(String(15), nullable=False)
    SupplierCode = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierTaxTo = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierDocNo = Column(String(20), nullable=False)
    TaxNo = Column(String(20), nullable=False)
    TaxDate = Column(Date, nullable=False)
    Currency = Column(String(3), ForeignKey('mastercurrency.Code'), nullable=False)
    ExchangeRate = Column(Numeric(18, 4), nullable=False)
    TaxStatus = Column(String(10), nullable=False)
    TaxPercent = Column(Numeric(18, 4), nullable=False)
    TaxPrefix = Column(String(3), nullable=False)
    DiscPercent = Column(Numeric(18, 4), nullable=False)
    TotalGross = Column(Numeric(18, 4), nullable=False)
    TotalDisc = Column(Numeric(18, 4), nullable=False)
    TaxValue = Column(Numeric(18, 4), nullable=False)
    TaxValueInTaxCur = Column(Numeric(18, 4), nullable=False)
    TotalNetto = Column(Numeric(18, 4), nullable=False)
    TotalCost = Column(Numeric(18, 4), nullable=False)
    Information = Column(String(255), nullable=False)
    Status = Column(String(20), nullable=False)
    PrintCounter = Column(Integer, nullable=False)
    PrintedBy = Column(String(16), nullable=True)
    PrintedDate = Column(DateTime, nullable=True)
    CreatedBy = Column(String(16), nullable=False)
    CreatedDate = Column(DateTime, nullable=False)
    ChangedBy = Column(String(16), nullable=False)
    ChangedDate = Column(DateTime, nullable=False)

    supplier_ref = relationship("MasterSupplier", foreign_keys=[SupplierCode])
    supplier_tax_to_ref = relationship("MasterSupplier", foreign_keys=[SupplierTaxTo])
    currency_ref = relationship("MasterCurrency")
    details = relationship("PurchaseReturnD", back_populates="header", cascade="all, delete-orphan")


class PurchaseReturnD(Base):
    __tablename__ = 'purchasereturnd'

    DocNo = Column(String(15), ForeignKey('purchasereturnh.DocNo'), primary_key=True)
    Number = Column(Integer, primary_key=True)
    MaterialCode = Column(String(20), ForeignKey('mastermaterial.Code'), primary_key=True)
    Info = Column(String(1024), nullable=False)
    TagNo = Column(String(10), primary_key=True)
    Unit = Column(String(5), ForeignKey('masterunit.Code'), nullable=False)
    Qty = Column(Numeric(18, 4), nullable=False)
    Price = Column(Numeric(18, 4), nullable=False)
    Gross = Column(Numeric(18, 4), nullable=False)
    DiscPercent = Column(Numeric(18, 4), nullable=False)
    DiscPercent2 = Column(Numeric(18, 4), nullable=False)
    DiscPercent3 = Column(Numeric(18, 4), nullable=False)
    DiscValue = Column(Numeric(18, 4), nullable=False)
    DiscNominal = Column(Numeric(18, 4), nullable=False)
    Netto = Column(Numeric(18, 4), nullable=False)
    Cost = Column(Numeric(18, 4), nullable=False)

    header = relationship("PurchaseReturnH", back_populates="details")
    material_ref = relationship("MasterMaterial")
    unit_ref = relationship("MasterUnit")

class PurchaseInvoiceH(Base):
    __tablename__ = 'purchaseinvoiceh'

    DocNo = Column(String(15), primary_key=True)
    Series = Column(String(3), nullable=False)
    DocDate = Column(Date, nullable=False)
    PODocNo = Column(String(15), nullable=False)
    JODocNo = Column(String(15), nullable=False)
    Trip = Column(String(20), nullable=False)
    TransactionType = Column(String(20), nullable=False)
    GRDocNo = Column(String(15), nullable=False)
    Location = Column(String(5), nullable=False)
    SupplierCode = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierTaxTo = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierInvNo = Column(String(20), nullable=False)
    TOP = Column(Integer, nullable=False)
    Currency = Column(String(3), ForeignKey('mastercurrency.Code'), nullable=False)
    ExchangeRate = Column(Numeric(18, 4), nullable=False)
    TotalCost = Column(Numeric(18, 4), nullable=False)
    CostDistribution = Column(String(10), nullable=False)
    TaxStatus = Column(String(10), nullable=False)
    TaxPercent = Column(Numeric(18, 4), nullable=False)
    TaxPrefix = Column(String(3), nullable=False)
    TaxNo = Column(String(25), nullable=False)
    DiscPercent = Column(Numeric(18, 4), nullable=False)
    TotalGross = Column(Numeric(18, 4), nullable=False)
    TotalDisc = Column(Numeric(18, 4), nullable=False)
    DownPayment = Column(Numeric(18, 4), nullable=False)
    TaxValue = Column(Numeric(18, 4), nullable=False)
    TaxValueInTaxCur = Column(Numeric(18, 4), nullable=False)
    TotalNetto = Column(Numeric(18, 4), nullable=False)
    CutPPh = Column(BIT, nullable=False)
    PPhPercent = Column(Numeric(18, 4), nullable=False)
    PPhValue = Column(Numeric(18, 4), nullable=False)
    Information = Column(String(255), nullable=False)
    Status = Column(String(20), nullable=False)
    PrintCounter = Column(Integer, nullable=False)
    PrintedBy = Column(String(16), nullable=True)
    PrintedDate = Column(DateTime, nullable=True)
    CreatedBy = Column(String(16), nullable=False)
    CreatedDate = Column(DateTime, nullable=False)
    ChangedBy = Column(String(20), nullable=False)
    ChangedDate = Column(DateTime, nullable=False)

    supplier_ref = relationship("MasterSupplier", foreign_keys=[SupplierCode])
    supplier_tax_to_ref = relationship("MasterSupplier", foreign_keys=[SupplierTaxTo])
    currency_ref = relationship("MasterCurrency")
    # Definisikan relasi ke tabel detail yang merujuk ke sini
    costs = relationship("PurchaseInvoiceC", back_populates="header")
    down_payments = relationship("PurchaseInvoiceDP", back_populates="header")
    goods_receipts = relationship("PurchaseInvoiceGR", back_populates="header")
    # Tambahkan relasi ke PurchaseInvoiceD jika sudah ada
    # details = relationship("PurchaseInvoiceD", back_populates="header")

class PurchaseCostH(Base):
    __tablename__ = 'purchasecosth'
    DocNo = Column(String(15), primary_key=True)
    # ... (tambahkan semua kolom dari skema)
    Series = Column(String(3), nullable=False)
    DocDate = Column(Date, nullable=False)
    TransactionType = Column(String(20), nullable=False)
    SupplierCode = Column(String(10), ForeignKey('mastersupplier.Code'), nullable=False)
    SupplierTaxTo = Column(String(10), nullable=False)
    SupplierInvNo = Column(String(20), nullable=False)
    TOP = Column(Integer, nullable=False)
    TaxStatus = Column(String(10), nullable=False)
    TaxPercent = Column(Numeric(18, 4), nullable=False)
    TaxPrefix = Column(String(3), nullable=False)
    TaxNo = Column(String(25), nullable=False)
    Currency = Column(String(3), ForeignKey('mastercurrency.Code'), nullable=False)
    ExchangeRate = Column(Numeric(18, 4), nullable=False)
    TotalCost = Column(Numeric(18, 4), nullable=False)
    TaxValue = Column(Numeric(18, 4), nullable=False)
    TaxValueInTaxCur = Column(Numeric(18, 4), nullable=False)
    TotalNetto = Column(Numeric(18, 4), nullable=False)
    Information = Column(String(255), nullable=False)
    InvoiceDocNo = Column(String(15), nullable=False)
    Status = Column(String(20), nullable=False)
    IsApproved = Column(BIT, nullable=False)
    ApprovedBy = Column(String(16), nullable=True)
    ApprovedDate = Column(DateTime, nullable=True)
    PrintCounter = Column(Integer, nullable=False)
    PrintedBy = Column(String(16), nullable=True)
    PrintedDate = Column(DateTime, nullable=True)
    CreatedBy = Column(String(16), nullable=False)
    CreatedDate = Column(DateTime, nullable=False)
    ChangedBy = Column(String(16), nullable=False)
    ChangedDate = Column(DateTime, nullable=False)

    supplier_ref = relationship("MasterSupplier")
    currency_ref = relationship("MasterCurrency")
    details = relationship("PurchaseCostD", back_populates="header")

class PurchaseCostD(Base):
    __tablename__ = 'purchasecostd'
    DocNo = Column(String(15), ForeignKey('purchasecosth.DocNo'), primary_key=True)
    Description = Column(String(50), primary_key=True)
    Cost = Column(Numeric(18, 4), nullable=False)
    header = relationship("PurchaseCostH", back_populates="details")

class PurchaseInvoiceC(Base):
    __tablename__ = 'purchaseinvoicec'
    DocNo = Column(String(15), ForeignKey('purchaseinvoiceh.DocNo'), primary_key=True)
    PCDocNo = Column(String(15), primary_key=True)
    header = relationship("PurchaseInvoiceH", back_populates="costs")

class PurchaseInvoiceDP(Base):
    __tablename__ = 'purchaseinvoicedp'
    DocNo = Column(String(15), ForeignKey('purchaseinvoiceh.DocNo'), primary_key=True)
    DPDocNo = Column(String(16), primary_key=True)
    Usage = Column(Numeric(18, 4), nullable=False)
    header = relationship("PurchaseInvoiceH", back_populates="down_payments")

class PurchaseInvoiceGR(Base):
    __tablename__ = 'purchaseinvoicegr'
    DocNo = Column(String(15), ForeignKey('purchaseinvoiceh.DocNo'), primary_key=True)
    GRDocNo = Column(String(15), primary_key=True)
    header = relationship("PurchaseInvoiceH", back_populates="goods_receipts")